#!/usr/bin/env python3
"""Learn site-specific parental ALT observation probabilities from pure-parent controls.

The input is one or more .mt_site_counts.tsv files generated by mt_fusion_ratio
in --calibration_reference mode.  Counts are aggregated by assay/stratum,
canonical parent pair, site, and true parent, then shrunk toward the expected
parental state so probabilities are never exactly zero or one.
"""
from __future__ import annotations
import argparse
import os
from datetime import datetime, timezone
import numpy as np
import pandas as pd

REQUIRED = {
    "library_id", "chrom", "pos", "parent1_state", "parent2_state",
    "ref_molecules", "alt_molecules", "calibration_true_parent",
    "assay_mode", "canonical_parent1", "canonical_parent2",
}
OUT_COLUMNS = [
    "calibration_id", "assay_mode", "library_or_stratum",
    "canonical_parent1", "canonical_parent2", "chrom", "pos", "parent",
    "ref_molecules", "alt_molecules", "alt_probability", "calibration_status",
]

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--site-counts", nargs="+", required=True)
    p.add_argument("--output", required=True)
    p.add_argument("--calibration-id", required=True)
    p.add_argument("--stratum-column", default="library_id",
                   help="Input column used for library_or_stratum [library_id]")
    p.add_argument("--prior-strength", type=float, default=20.0)
    p.add_argument("--error-rate", type=float, default=0.005)
    p.add_argument("--min-molecules", type=int, default=10)
    p.add_argument("--run-parameters", default=None)
    return p.parse_args()

def read_inputs(paths: list[str], stratum_column: str) -> pd.DataFrame:
    frames = []
    for path in paths:
        df = pd.read_csv(path, sep="\t", dtype={"barcode": str})
        missing = sorted(REQUIRED - set(df.columns))
        if stratum_column not in df.columns:
            missing.append(stratum_column)
        if missing:
            raise ValueError(f"{path}: missing required column(s): {', '.join(sorted(set(missing)))}")
        df = df.copy()
        df["_source"] = path
        frames.append(df)
    if not frames:
        raise ValueError("No site-count inputs")
    return pd.concat(frames, ignore_index=True)

def main() -> None:
    args = parse_args()
    if not (0.0 < args.error_rate < 0.5):
        raise SystemExit("--error-rate must satisfy 0 < value < 0.5")
    if args.prior_strength <= 0:
        raise SystemExit("--prior-strength must be > 0")
    if args.min_molecules < 0:
        raise SystemExit("--min-molecules must be >= 0")

    df = read_inputs(args.site_counts, args.stratum_column)
    for c in ["ref_molecules", "alt_molecules", "pos", "parent1_state", "parent2_state"]:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df = df[df["calibration_true_parent"].notna()].copy()
    df = df[~df["calibration_true_parent"].astype(str).isin(["", "NA", ".", "nan"])]
    df = df[df["used_in_fit"].astype(str).isin(["1", "1.0", "True", "true"])].copy() \
        if "used_in_fit" in df.columns else df
    if df.empty:
        raise SystemExit("No usable calibration-reference site rows found")

    rows = []
    group_cols = ["assay_mode", args.stratum_column, "canonical_parent1", "canonical_parent2", "chrom", "pos"]
    for key, g in df.groupby(group_cols, dropna=False, sort=True):
        assay, stratum, p1, p2, chrom, pos = key
        for parent, state_col in [(str(p1), "parent1_state"), (str(p2), "parent2_state")]:
            pg = g[g["calibration_true_parent"].astype(str) == parent]
            if pg.empty:
                continue
            # State is pair/site-defined; inconsistent input is a warranted error.
            states = sorted(set(int(x) for x in pg[state_col].dropna().astype(int)))
            if len(states) != 1 or states[0] not in (0, 1):
                raise ValueError(f"Inconsistent parental state for {parent} at {chrom}:{int(pos)}")
            ref = int(pg["ref_molecules"].fillna(0).sum())
            alt = int(pg["alt_molecules"].fillna(0).sum())
            total = ref + alt
            expected_alt = (1.0 - args.error_rate) if states[0] == 1 else args.error_rate
            prob = (alt + args.prior_strength * expected_alt) / (total + args.prior_strength)
            # Numerical safety while preserving shrinkage semantics.
            prob = float(np.clip(prob, np.finfo(float).eps, 1.0 - np.finfo(float).eps))
            status = "PASS" if total >= args.min_molecules else "SHRUNK_LOW_COUNTS"
            rows.append({
                "calibration_id": args.calibration_id,
                "assay_mode": str(assay),
                "library_or_stratum": str(stratum),
                "canonical_parent1": str(p1),
                "canonical_parent2": str(p2),
                "chrom": str(chrom),
                "pos": int(pos),
                "parent": parent,
                "ref_molecules": ref,
                "alt_molecules": alt,
                "alt_probability": prob,
                "calibration_status": status,
            })
    out = pd.DataFrame(rows, columns=OUT_COLUMNS)
    if out.empty:
        raise SystemExit("No parent/site calibration rows could be estimated")
    os.makedirs(os.path.dirname(os.path.abspath(args.output)) or ".", exist_ok=True)
    out.to_csv(args.output, sep="\t", index=False, float_format="%.12g")

    params = args.run_parameters or args.output + ".run_parameters.tsv"
    pdata = [
        ("calibration_id", args.calibration_id),
        ("site_counts", ";".join(args.site_counts)),
        ("stratum_column", args.stratum_column),
        ("prior_strength", args.prior_strength),
        ("error_rate", args.error_rate),
        ("min_molecules", args.min_molecules),
        ("output_rows", len(out)),
        ("timestamp_utc", datetime.now(timezone.utc).isoformat()),
        ("pandas_version", pd.__version__),
        ("numpy_version", np.__version__),
    ]
    pd.DataFrame(pdata, columns=["parameter", "value"]).to_csv(params, sep="\t", index=False)
    print(f"Wrote {len(out)} calibration rows: {args.output}")

if __name__ == "__main__":
    main()
